### ISSUE TITLE
Strong vs Span

### ISSUE THREAD

**Issue by mikebutts** [ecipra/prj-rev-bwfs-dasmoto#2]
https://github.com/ecipra/prj-rev-bwfs-dasmoto/blob/3c900282fb2c39c56251e52d7801f067db3f19cd/U2D6_Dasmotos/index.html#L26

Strong tags were made for making a bold statement. Spans were made to style a blurb of text inside of an element, keep this in mind for future projects, also consider using a class for larger projects.

**Comment by ecipra** [comment]
Ah good feedback. Will use <span> instead when additional styling (like this) is required.
