### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [ecipra/prj-rev-bwfs-dasmoto#3]
Meets Expectation

Well done on this project it comes very close to spec. This project was neatly written, I recommended using divs anytime you want to section of code. For something this basic, it is not a big deal but a good habit to start when working on large projects. Same with span, good habit to use spans for styling text, also using classes on those spans. Next, try to spice up the page, maybe add a background image for the header or some colors to the divs. Coolors.co has some cool schemes you can check out. Another idea is centering the image and text so it's not all left aligned.

**Comment by ecipra** [comment]
Thanks Michael! Appreciate the feedback. 

I didn't realize we could go a little wild with styling (e.g. colors, backgrounds, etc.)! As a designer by trade I'll see what I can do to kick it up a notch next time :)
